version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot-container
    ports:
      - "9090:8080"
    networks:
      - app-network
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root


  postgres_db:
    image: postgres:16
    container_name: postgres-container
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge