package ru.lesson.thesurveytgbot;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.scheduling.annotation.EnableAsync;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@EnableAsync
public class TheSurveyTgBotApplication {

    public static void main(String[] args) {
        SpringApplication.run(TheSurveyTgBotApplication.class, args);
    }

}
